services:
  - type: web
    name: zhujia-shop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://xbjyf_user:pKaqOTvViL8ZVxFIJxcEuD2vuFE1CBvX@dpg-cv2on7lumphs739t5f6g-a.singapore-postgres.render.com/xbjyf